### ISSUE TITLE
Issue with Pronto and GO Ontology.

### ISSUE THREAD

**Issue by ArnaudBelcour** [AuReMe/emapper2gbk#5]
* eggnog2gbk version: 0.1.0
* Python version: 3.7
* Operating System: Linux

### Description

If you try to use emapper2gbk with the new `go-basic.obo` file there is  an error with pronto. Pronto will return the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pronto/ontology.py", line 283, in __init__
    cls(self).parse_from(_handle)  # type: ignore
  File "/usr/local/lib/python3.6/dist-packages/pronto/parsers/obo.py", line 45, in parse_from
    raise SyntaxError(s.args[0], location) from None
  File "http://purl.obolibrary.org/obo/go/snapshot/go.obo", line 436334
    def: "Catalysis of the reaction: behenoyl-CoA(4-) + malonyl-CoA(5-) + H+ <=> 3-oxotetracosanoyl-CoA. + carbon dioxide + coenzyme A." [GOC:pz, Rhea: 36507]␊
                                                                                                                                                        ^
SyntaxError: expected QuotedString
```

This is linked to an issue in the current go-basic.obo file (`format-version: 1.2, data-version: releases/2021-06-16`) due to the space in `Rhea: 36507`. The issue has been fixed in https://github.com/geneontology/go-ontology/commit/104252cc533a83248ed4df2caefd434e6eb8b531. Before the fix is released in the new version of `go-basic.obo` you can either download the current `go-basic.obo` (which can be downloaded at this address: http://purl.obolibrary.org/obo/go/go-basic.obo) and manually corrects the Rhea ID (which is associated to the GO Term GO:0102338). Or you can use an old version of `go-basic.obo` like the [one](https://github.com/AuReMe/emapper2gbk/blob/master/tests/go-basic.obo) in the test folder of emapper2gbk.

**Comment by ArnaudBelcour** [comment]
This issue has been fixed in the release `format-version: 1.2 data-version: releases/2021-07-02`.
